phone:
  country: KR

jwt:
  secret-key: MLIt3kWFcIhNyEHoqg3YhOnR17sFMsejSO1rG2dKtz0ciaigS7axiIKSKW0boedjmELen/ImSDPLNUShCEs4Kw==
  expiration-millis: 7200000 # 2시간

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

